# version: "3.5"
# services:
#   web:
#     build: .
#     ports:
#       - target: 8080
#         published: 8080
#     depends_on:
#       - mongodb
#     volumes:
#       - "mongodata:/data/db"

#   db:
#     image: mongo
#     ports:
#       -"27017:27017"

# networks:
#   counter-net:

# volumes:
#   counter-vol:

version: '3.7'

services:

  webapp:
    image: webapp
    ports:
      - 8080:8080
    networks:
      - mynetwork

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "mongodata:/data/db"
    networks:
      - mynetwork

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - mynetwork
volumes:
  mongodata:

networks:
  mynetwork: